# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

project_name: default
project_root: ~/work/default
rvm: ree
tabs:
  - server: script/server
  - bash: git wtf
  - vim: vim
  - console: script/console
  - bash: tail -f log/development.log
