# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

project_name: default
project_root: ~/work/default
rvm: ree
tabs:
  - server: rails server
  - bash: 
  - vim: vim
  - console: rails console
  - bash: 
